TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#DB += ADQInfo.template ADQAIChannelGroup.template ADQAIChannel.template tspd-adq.substitutions4 tspd-adq.substitutions8 ADQMessageLog.template
DB += tspd-adq.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
